name: Create Keystore

on:
  workflow_dispatch:

jobs:
  create-keystore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'

      - name: Create keystore
        run: |
          set -euo pipefail
          KEYSTORE=keystore.jks
          ALIAS=key1
          STOREPASS='Dennisd-401!'
          KEYPASS='Dennisd-401!'
          if [ -f "$KEYSTORE" ]; then echo "$KEYSTORE already exists, aborting"; exit 1; fi
          keytool -genkeypair -v -storetype JKS -keystore "$KEYSTORE" -alias "$ALIAS" -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass "$STOREPASS" -keypass "$KEYPASS" -dname 'CN=OpenLauncher, OU=Dev, O=OpenLauncher, L=Unknown, S=Unknown, C=US'
          chmod 600 "$KEYSTORE"

      - name: Upload keystore artifact
        uses: actions/upload-artifact@v4
        with:
          name: keystore
          path: keystore.jks